### PR TITLE
 3D secure supported with new 3DS2

### PR DESCRIPTION
**Pull request by jigarsangoi**
Hi @skoshelev ,

I try to contribute code for 3D secure with new 3DS2.
I am using javascript library of version 3.50 & Braintree DLL 4.1.3

There is 1 thing I want to tell you is, Its working fine in Sandbox environment 
But while testing I used 2 different cards. I mentioned them below with result

Visa = My card verified and got popup which ask me to validate my transaction with OTP (one time password). Money deducted but order not created because of error "Gateway rejected, reason = AVS and CVV". I m not sure why did I get this error because we have AVS and CVV verification for USA only & this card registered in India.

American Express = My card verified because I don't see any error in console but I don't see popup to verify transaction with OTP because liabilityShifted = false

Please test this solution in live environment. In case if you have any question about my code please ask me.

Thanks

### CODE REVIEW

**Comment by skoshelev** [comment]
Hi @jigarsangoi. Thank you very much for your help, I looked at your code and tested it, everything worked without problems on our test card, if you let me, we would like to take your code as a basis for implementing 3DS2 for version 4.20, and your pull-quest I will put in a separate thread for those who wants to get this function for 4.10

**Comment by jigarsangoi** [comment]
Hi @skoshelev Please go ahead. I don't have any problem with that.

**Comment by skoshelev** [comment]
Hi @jigarsangoi. Thank you very much for your contribution in our code

**Comment by skoshelev** [comment]
Merged into [separate branch](https://github.com/nopSolutions/braintree-plugin-for-nopcommerce/tree/nopCommerce-4.10_with_3DS )

**Comment by jigarsangoi** [comment]
@skoshelev There is 1 change in code, How can I submit here ? shall I generate new pull request ?

**Comment by skoshelev** [comment]
Hi @jigarsangoi, You can add changes to this PR, then I will transfer them to the branch

**Comment by jigarsangoi** [comment]
@skoshelev I pushed my changes now you can merge it. These changes are used to verify AVS in braintree.

**Comment by skoshelev** [comment]
Hi @jigarsangoi. Thank you for your help again.

**Pull request closed without merging**
